export const GET_RESOURCES = 'GET_RESOURCES';
export const GET_INTRODUCTION = 'GET_INTRODUCTION';
export const GET_WRAP_UP = 'GET_WRAP_UP';

export const MARK_INTRODUCTION_COMPLETE = 'MARK_INTRODUCTION_COMPLETE';
export const MARK_RESOURCE_COMPLETE = 'MARK_RESOURCE_COMPLETE';
export const MARK_WRAP_UP_COMPLETE = 'MARK_WRAP_UP_COMPLETE';

export const CLOSE_INTRO = 'CLOSE_INTRO';
